// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteSourcePerigonRequest struct {
	SourceID string `pathParam:"style=simple,explode=false,name=sourceId"`
}

func (d *DeleteSourcePerigonRequest) GetSourceID() string {
	if d == nil {
		return ""
	}
	return d.SourceID
}

type DeleteSourcePerigonResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteSourcePerigonResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteSourcePerigonResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteSourcePerigonResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
