// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type GetSourceGnewsRequest struct {
	SourceID string `pathParam:"style=simple,explode=false,name=sourceId"`
}

func (g *GetSourceGnewsRequest) GetSourceID() string {
	if g == nil {
		return ""
	}
	return g.SourceID
}

type GetSourceGnewsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Get a Source by the id in the path.
	SourceResponse *shared.SourceResponse
}

func (g *GetSourceGnewsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSourceGnewsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSourceGnewsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSourceGnewsResponse) GetSourceResponse() *shared.SourceResponse {
	if g == nil {
		return nil
	}
	return g.SourceResponse
}
