// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type PutDestinationKafkaRequest struct {
	DestinationID              string                            `pathParam:"style=simple,explode=false,name=destinationId"`
	DestinationKafkaPutRequest shared.DestinationKafkaPutRequest `request:"mediaType=application/json"`
}

func (p *PutDestinationKafkaRequest) GetDestinationID() string {
	if p == nil {
		return ""
	}
	return p.DestinationID
}

func (p *PutDestinationKafkaRequest) GetDestinationKafkaPutRequest() shared.DestinationKafkaPutRequest {
	if p == nil {
		return shared.DestinationKafkaPutRequest{}
	}
	return p.DestinationKafkaPutRequest
}

type PutDestinationKafkaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PutDestinationKafkaResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutDestinationKafkaResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutDestinationKafkaResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
