// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type PutDestinationChromaRequest struct {
	DestinationID               string                             `pathParam:"style=simple,explode=false,name=destinationId"`
	DestinationChromaPutRequest shared.DestinationChromaPutRequest `request:"mediaType=application/json"`
}

func (p *PutDestinationChromaRequest) GetDestinationID() string {
	if p == nil {
		return ""
	}
	return p.DestinationID
}

func (p *PutDestinationChromaRequest) GetDestinationChromaPutRequest() shared.DestinationChromaPutRequest {
	if p == nil {
		return shared.DestinationChromaPutRequest{}
	}
	return p.DestinationChromaPutRequest
}

type PutDestinationChromaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The resource was updated successfully
	DestinationResponse *shared.DestinationResponse
}

func (p *PutDestinationChromaResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutDestinationChromaResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutDestinationChromaResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutDestinationChromaResponse) GetDestinationResponse() *shared.DestinationResponse {
	if p == nil {
		return nil
	}
	return p.DestinationResponse
}
