// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type PutSourceRequest struct {
	SourceID         string                   `pathParam:"style=simple,explode=false,name=sourceId"`
	SourcePutRequest *shared.SourcePutRequest `request:"mediaType=application/json"`
}

func (p *PutSourceRequest) GetSourceID() string {
	if p == nil {
		return ""
	}
	return p.SourceID
}

func (p *PutSourceRequest) GetSourcePutRequest() *shared.SourcePutRequest {
	if p == nil {
		return nil
	}
	return p.SourcePutRequest
}

type PutSourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update a source and fully overwrite it
	SourceResponse *shared.SourceResponse
}

func (p *PutSourceResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutSourceResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutSourceResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutSourceResponse) GetSourceResponse() *shared.SourceResponse {
	if p == nil {
		return nil
	}
	return p.SourceResponse
}
