// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type PutSourceGocardlessRequest struct {
	SourceID                   string                             `pathParam:"style=simple,explode=false,name=sourceId"`
	SourceGocardlessPutRequest *shared.SourceGocardlessPutRequest `request:"mediaType=application/json"`
}

func (o *PutSourceGocardlessRequest) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

func (o *PutSourceGocardlessRequest) GetSourceGocardlessPutRequest() *shared.SourceGocardlessPutRequest {
	if o == nil {
		return nil
	}
	return o.SourceGocardlessPutRequest
}

type PutSourceGocardlessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutSourceGocardlessResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutSourceGocardlessResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutSourceGocardlessResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
