// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type PutSourcePendoRequest struct {
	SourceID              string                       `pathParam:"style=simple,explode=false,name=sourceId"`
	SourcePendoPutRequest shared.SourcePendoPutRequest `request:"mediaType=application/json"`
}

func (p *PutSourcePendoRequest) GetSourceID() string {
	if p == nil {
		return ""
	}
	return p.SourceID
}

func (p *PutSourcePendoRequest) GetSourcePendoPutRequest() shared.SourcePendoPutRequest {
	if p == nil {
		return shared.SourcePendoPutRequest{}
	}
	return p.SourcePendoPutRequest
}

type PutSourcePendoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The resource was updated successfully
	SourceResponse *shared.SourceResponse
}

func (p *PutSourcePendoResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutSourcePendoResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutSourcePendoResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutSourcePendoResponse) GetSourceResponse() *shared.SourceResponse {
	if p == nil {
		return nil
	}
	return p.SourceResponse
}
