// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type PutSourceOncehubRequest struct {
	SourceID                string                         `pathParam:"style=simple,explode=false,name=sourceId"`
	SourceOncehubPutRequest shared.SourceOncehubPutRequest `request:"mediaType=application/json"`
}

func (p *PutSourceOncehubRequest) GetSourceID() string {
	if p == nil {
		return ""
	}
	return p.SourceID
}

func (p *PutSourceOncehubRequest) GetSourceOncehubPutRequest() shared.SourceOncehubPutRequest {
	if p == nil {
		return shared.SourceOncehubPutRequest{}
	}
	return p.SourceOncehubPutRequest
}

type PutSourceOncehubResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The resource was updated successfully
	SourceResponse *shared.SourceResponse
}

func (p *PutSourceOncehubResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutSourceOncehubResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutSourceOncehubResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutSourceOncehubResponse) GetSourceResponse() *shared.SourceResponse {
	if p == nil {
		return nil
	}
	return p.SourceResponse
}
