// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type JobStatusEnumEnum string

const (
	JobStatusEnumEnumPending    JobStatusEnumEnum = "pending"
	JobStatusEnumEnumRunning    JobStatusEnumEnum = "running"
	JobStatusEnumEnumIncomplete JobStatusEnumEnum = "incomplete"
	JobStatusEnumEnumFailed     JobStatusEnumEnum = "failed"
	JobStatusEnumEnumSucceeded  JobStatusEnumEnum = "succeeded"
	JobStatusEnumEnumCancelled  JobStatusEnumEnum = "cancelled"
)

func (e JobStatusEnumEnum) ToPointer() *JobStatusEnumEnum {
	return &e
}

func (e *JobStatusEnumEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "running":
		fallthrough
	case "incomplete":
		fallthrough
	case "failed":
		fallthrough
	case "succeeded":
		fallthrough
	case "cancelled":
		*e = JobStatusEnumEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobStatusEnumEnum: %v", v)
	}
}
