// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceTvmazeScheduleTvmazeScheduleEnum string

const (
	SourceTvmazeScheduleTvmazeScheduleEnumTvmazeSchedule SourceTvmazeScheduleTvmazeScheduleEnum = "tvmaze-schedule"
)

func (e *SourceTvmazeScheduleTvmazeScheduleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "tvmaze-schedule":
		*e = SourceTvmazeScheduleTvmazeScheduleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceTvmazeScheduleTvmazeScheduleEnum: %s", s)
	}
}

// SourceTvmazeSchedule - The values required to configure the source.
type SourceTvmazeSchedule struct {
	// Country code for domestic TV schedule retrieval.
	DomesticScheduleCountryCode string `json:"domestic_schedule_country_code"`
	// End date for TV schedule retrieval. May be in the future. Optional.
	//
	EndDate    *string                                `json:"end_date,omitempty"`
	SourceType SourceTvmazeScheduleTvmazeScheduleEnum `json:"sourceType"`
	// Start date for TV schedule retrieval. May be in the future.
	StartDate string `json:"start_date"`
	// ISO 3166-1 country code for web TV schedule retrieval. Leave blank for
	// all countries plus global web channels (e.g. Netflix). Alternatively,
	// set to 'global' for just global web channels.
	//
	WebScheduleCountryCode *string `json:"web_schedule_country_code,omitempty"`
}
