// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type SourceMailgunUpdate struct {
	// Domain region code. 'EU' or 'US' are possible values. The default is 'US'.
	DomainRegion *string `json:"domain_region,omitempty"`
	// Primary account API key to access your Mailgun data.
	PrivateKey string `json:"private_key"`
	// UTC date and time in the format 2020-10-01 00:00:00. Any data before this date will not be replicated. If omitted, defaults to 3 days ago.
	StartDate *time.Time `json:"start_date,omitempty"`
}
