// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

type DestinationWeaviateCreateRequest struct {
	// Name of the destination e.g. dev-mysql-instance.
	Name string `json:"name"`
	// The UUID of the connector definition. One of configuration.destinationType or definitionId must be provided.
	DefinitionID *string `default:"7b7d7a0d-954c-45a0-bcfc-39a634b97736" json:"definitionId"`
	WorkspaceID  string  `json:"workspaceId"`
	// The configuration model for the Vector DB based destinations. This model is used to generate the UI for the destination configuration, as well as to provide type safety for the configuration passed to the destination. The configuration model is composed of four parts: * Processing configuration * Embedding configuration * Indexing configuration * Advanced configuration Processing, embedding and advanced configuration are provided by this base class, while the indexing configuration is provided by the destination connector in the sub class.
	Configuration DestinationWeaviate `json:"configuration"`
}

func (d DestinationWeaviateCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationWeaviateCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DestinationWeaviateCreateRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DestinationWeaviateCreateRequest) GetDefinitionID() *string {
	if d == nil {
		return nil
	}
	return d.DefinitionID
}

func (d *DestinationWeaviateCreateRequest) GetWorkspaceID() string {
	if d == nil {
		return ""
	}
	return d.WorkspaceID
}

func (d *DestinationWeaviateCreateRequest) GetConfiguration() DestinationWeaviate {
	if d == nil {
		return DestinationWeaviate{}
	}
	return d.Configuration
}
