// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EmailNotificationConfig - Configures an email notification.
type EmailNotificationConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EmailNotificationConfig) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}
