// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceActivecampaignUpdate struct {
	// Account Username
	AccountUsername string `json:"account_username"`
	// API Key
	APIKey string `json:"api_key"`
}

func (o *SourceActivecampaignUpdate) GetAccountUsername() string {
	if o == nil {
		return ""
	}
	return o.AccountUsername
}

func (o *SourceActivecampaignUpdate) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}
