// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceHibobCreateRequest struct {
	// Name of the source e.g. dev-mysql-instance.
	Name string `json:"name"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided.
	DefinitionID  *string     `json:"definitionId,omitempty"`
	WorkspaceID   string      `json:"workspaceId"`
	Configuration SourceHibob `json:"configuration"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretID *string `json:"secretId,omitempty"`
}

func (s *SourceHibobCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceHibobCreateRequest) GetDefinitionID() *string {
	if s == nil {
		return nil
	}
	return s.DefinitionID
}

func (s *SourceHibobCreateRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourceHibobCreateRequest) GetConfiguration() SourceHibob {
	if s == nil {
		return SourceHibob{}
	}
	return s.Configuration
}

func (s *SourceHibobCreateRequest) GetSecretID() *string {
	if s == nil {
		return nil
	}
	return s.SecretID
}
