// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceFreshdeskPutRequest struct {
	Name          string                `json:"name"`
	WorkspaceID   string                `json:"workspaceId"`
	Configuration SourceFreshdeskUpdate `json:"configuration"`
}

func (s *SourceFreshdeskPutRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceFreshdeskPutRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourceFreshdeskPutRequest) GetConfiguration() SourceFreshdeskUpdate {
	if s == nil {
		return SourceFreshdeskUpdate{}
	}
	return s.Configuration
}
