// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourcePivotalTrackerPutRequest struct {
	Name          string                     `json:"name"`
	WorkspaceID   string                     `json:"workspaceId"`
	Configuration SourcePivotalTrackerUpdate `json:"configuration"`
}

func (s *SourcePivotalTrackerPutRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourcePivotalTrackerPutRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourcePivotalTrackerPutRequest) GetConfiguration() SourcePivotalTrackerUpdate {
	if s == nil {
		return SourcePivotalTrackerUpdate{}
	}
	return s.Configuration
}
