// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceUsCensusPutRequest struct {
	Name          string               `json:"name"`
	WorkspaceID   string               `json:"workspaceId"`
	Configuration SourceUsCensusUpdate `json:"configuration"`
}

func (o *SourceUsCensusPutRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SourceUsCensusPutRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *SourceUsCensusPutRequest) GetConfiguration() SourceUsCensusUpdate {
	if o == nil {
		return SourceUsCensusUpdate{}
	}
	return o.Configuration
}
