// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceYouNeedABudgetYnabCreateRequest struct {
	// Name of the source e.g. dev-mysql-instance.
	Name string `json:"name"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided.
	DefinitionID  *string                  `json:"definitionId,omitempty"`
	WorkspaceID   string                   `json:"workspaceId"`
	Configuration SourceYouNeedABudgetYnab `json:"configuration"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretID *string `json:"secretId,omitempty"`
}

func (s *SourceYouNeedABudgetYnabCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceYouNeedABudgetYnabCreateRequest) GetDefinitionID() *string {
	if s == nil {
		return nil
	}
	return s.DefinitionID
}

func (s *SourceYouNeedABudgetYnabCreateRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourceYouNeedABudgetYnabCreateRequest) GetConfiguration() SourceYouNeedABudgetYnab {
	if s == nil {
		return SourceYouNeedABudgetYnab{}
	}
	return s.Configuration
}

func (s *SourceYouNeedABudgetYnabCreateRequest) GetSecretID() *string {
	if s == nil {
		return nil
	}
	return s.SecretID
}
