// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
	"time"
)

type SourceBluetallySourceType string

const (
	SourceBluetallySourceTypeBluetally SourceBluetallySourceType = "bluetally"
)

func (e SourceBluetallySourceType) ToPointer() *SourceBluetallySourceType {
	return &e
}
func (e *SourceBluetallySourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bluetally":
		*e = SourceBluetallySourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceBluetallySourceType: %v", v)
	}
}

type SourceBluetally struct {
	// Your API key to authenticate with the BlueTally API. You can generate it by navigating to your account settings, selecting 'API Keys', and clicking 'Create API Key'.
	APIKey               string                     `json:"api_key"`
	StartDate            time.Time                  `json:"start_date"`
	sourceType           *SourceBluetallySourceType `const:"bluetally" json:"sourceType"`
	AdditionalProperties any                        `additionalProperties:"true" json:"-"`
}

func (s SourceBluetally) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceBluetally) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceBluetally) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}

func (s *SourceBluetally) GetStartDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartDate
}

func (s *SourceBluetally) GetSourceType() *SourceBluetallySourceType {
	return SourceBluetallySourceTypeBluetally.ToPointer()
}

func (s *SourceBluetally) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
