// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

type SourceConvexUpdateSourceType string

const (
	SourceConvexUpdateSourceTypeConvex SourceConvexUpdateSourceType = "convex"
)

func (e SourceConvexUpdateSourceType) ToPointer() *SourceConvexUpdateSourceType {
	return &e
}
func (e *SourceConvexUpdateSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "convex":
		*e = SourceConvexUpdateSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceConvexUpdateSourceType: %v", v)
	}
}

type SourceConvexUpdate struct {
	// API access key used to retrieve data from Convex.
	AccessKey            *string                       `json:"access_key,omitempty"`
	DeploymentURL        *string                       `json:"deployment_url,omitempty"`
	sourceType           *SourceConvexUpdateSourceType `const:"convex" json:"sourceType"`
	AdditionalProperties any                           `additionalProperties:"true" json:"-"`
}

func (s SourceConvexUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceConvexUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceConvexUpdate) GetAccessKey() *string {
	if s == nil {
		return nil
	}
	return s.AccessKey
}

func (s *SourceConvexUpdate) GetDeploymentURL() *string {
	if s == nil {
		return nil
	}
	return s.DeploymentURL
}

func (s *SourceConvexUpdate) GetSourceType() *SourceConvexUpdateSourceType {
	return SourceConvexUpdateSourceTypeConvex.ToPointer()
}

func (s *SourceConvexUpdate) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
