// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
	"time"
)

type SourceRechargeUpdateSourceType string

const (
	SourceRechargeUpdateSourceTypeRecharge SourceRechargeUpdateSourceType = "recharge"
)

func (e SourceRechargeUpdateSourceType) ToPointer() *SourceRechargeUpdateSourceType {
	return &e
}
func (e *SourceRechargeUpdateSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "recharge":
		*e = SourceRechargeUpdateSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceRechargeUpdateSourceType: %v", v)
	}
}

type SourceRechargeUpdate struct {
	// The value of the Access Token generated. See the <a href="https://docs.airbyte.com/integrations/sources/recharge">docs</a> for more information.
	AccessToken *string `json:"access_token,omitempty"`
	// Specifies how many days of historical data should be reloaded each time the recharge connector runs.
	LookbackWindowDays *int64 `default:"0" json:"lookback_window_days"`
	// The date from which you'd like to replicate data for Recharge API, in the format YYYY-MM-DDT00:00:00Z. Any data before this date will not be replicated.
	StartDate *time.Time `json:"start_date,omitempty"`
	// Define whether or not the `Orders` stream should use the deprecated `2021-01` API version, or use `2021-11`, otherwise.
	UseOrdersDeprecatedAPI *bool                           `default:"true" json:"use_orders_deprecated_api"`
	sourceType             *SourceRechargeUpdateSourceType `const:"recharge" json:"sourceType"`
	AdditionalProperties   any                             `additionalProperties:"true" json:"-"`
}

func (s SourceRechargeUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceRechargeUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceRechargeUpdate) GetAccessToken() *string {
	if s == nil {
		return nil
	}
	return s.AccessToken
}

func (s *SourceRechargeUpdate) GetLookbackWindowDays() *int64 {
	if s == nil {
		return nil
	}
	return s.LookbackWindowDays
}

func (s *SourceRechargeUpdate) GetStartDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartDate
}

func (s *SourceRechargeUpdate) GetUseOrdersDeprecatedAPI() *bool {
	if s == nil {
		return nil
	}
	return s.UseOrdersDeprecatedAPI
}

func (s *SourceRechargeUpdate) GetSourceType() *SourceRechargeUpdateSourceType {
	return SourceRechargeUpdateSourceTypeRecharge.ToPointer()
}

func (s *SourceRechargeUpdate) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
