// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

// SourceZonkaFeedbackUpdateDataCenterID - The identifier for the data center, such as 'us1' or 'e' for EU.
type SourceZonkaFeedbackUpdateDataCenterID string

const (
	SourceZonkaFeedbackUpdateDataCenterIDUs1 SourceZonkaFeedbackUpdateDataCenterID = "us1"
	SourceZonkaFeedbackUpdateDataCenterIDE   SourceZonkaFeedbackUpdateDataCenterID = "e"
)

func (e SourceZonkaFeedbackUpdateDataCenterID) ToPointer() *SourceZonkaFeedbackUpdateDataCenterID {
	return &e
}
func (e *SourceZonkaFeedbackUpdateDataCenterID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "us1":
		fallthrough
	case "e":
		*e = SourceZonkaFeedbackUpdateDataCenterID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceZonkaFeedbackUpdateDataCenterID: %v", v)
	}
}

type SourceZonkaFeedbackUpdateSourceType string

const (
	SourceZonkaFeedbackUpdateSourceTypeZonkaFeedback SourceZonkaFeedbackUpdateSourceType = "zonka-feedback"
)

func (e SourceZonkaFeedbackUpdateSourceType) ToPointer() *SourceZonkaFeedbackUpdateSourceType {
	return &e
}
func (e *SourceZonkaFeedbackUpdateSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "zonka-feedback":
		*e = SourceZonkaFeedbackUpdateSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceZonkaFeedbackUpdateSourceType: %v", v)
	}
}

type SourceZonkaFeedbackUpdate struct {
	// Auth token to use. Generate it by navigating to Company Settings > Developers > API in your Zonka Feedback account.
	AuthToken *string `json:"auth_token,omitempty"`
	// The identifier for the data center, such as 'us1' or 'e' for EU.
	Datacenter           *SourceZonkaFeedbackUpdateDataCenterID `json:"datacenter,omitempty"`
	sourceType           *SourceZonkaFeedbackUpdateSourceType   `const:"zonka-feedback" json:"sourceType"`
	AdditionalProperties any                                    `additionalProperties:"true" json:"-"`
}

func (s SourceZonkaFeedbackUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceZonkaFeedbackUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceZonkaFeedbackUpdate) GetAuthToken() *string {
	if s == nil {
		return nil
	}
	return s.AuthToken
}

func (s *SourceZonkaFeedbackUpdate) GetDatacenter() *SourceZonkaFeedbackUpdateDataCenterID {
	if s == nil {
		return nil
	}
	return s.Datacenter
}

func (s *SourceZonkaFeedbackUpdate) GetSourceType() *SourceZonkaFeedbackUpdateSourceType {
	return SourceZonkaFeedbackUpdateSourceTypeZonkaFeedback.ToPointer()
}

func (s *SourceZonkaFeedbackUpdate) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
