// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

type SourceYoutubeAnalyticsCreateRequest struct {
	// Name of the source e.g. dev-mysql-instance.
	Name string `json:"name"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided.
	DefinitionID  *string                `default:"afa734e4-3571-11ec-991a-1e0031268139" json:"definitionId"`
	WorkspaceID   string                 `json:"workspaceId"`
	Configuration SourceYoutubeAnalytics `json:"configuration"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretID *string `json:"secretId,omitempty"`
}

func (s SourceYoutubeAnalyticsCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceYoutubeAnalyticsCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceYoutubeAnalyticsCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceYoutubeAnalyticsCreateRequest) GetDefinitionID() *string {
	if s == nil {
		return nil
	}
	return s.DefinitionID
}

func (s *SourceYoutubeAnalyticsCreateRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourceYoutubeAnalyticsCreateRequest) GetConfiguration() SourceYoutubeAnalytics {
	if s == nil {
		return SourceYoutubeAnalytics{}
	}
	return s.Configuration
}

func (s *SourceYoutubeAnalyticsCreateRequest) GetSecretID() *string {
	if s == nil {
		return nil
	}
	return s.SecretID
}
