// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

type SourceCartCreateRequest struct {
	// Name of the source e.g. dev-mysql-instance.
	Name string `json:"name"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided.
	DefinitionID  *string    `default:"bb1a6d31-6879-4819-a2bd-3eed299ea8e2" json:"definitionId"`
	WorkspaceID   string     `json:"workspaceId"`
	Configuration SourceCart `json:"configuration"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretID *string `json:"secretId,omitempty"`
}

func (s SourceCartCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceCartCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceCartCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceCartCreateRequest) GetDefinitionID() *string {
	if s == nil {
		return nil
	}
	return s.DefinitionID
}

func (s *SourceCartCreateRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourceCartCreateRequest) GetConfiguration() SourceCart {
	if s == nil {
		return SourceCart{}
	}
	return s.Configuration
}

func (s *SourceCartCreateRequest) GetSecretID() *string {
	if s == nil {
		return nil
	}
	return s.SecretID
}
