// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceZapsignPutRequest struct {
	Name          string              `json:"name"`
	WorkspaceID   string              `json:"workspaceId"`
	Configuration SourceZapsignUpdate `json:"configuration"`
}

func (o *SourceZapsignPutRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SourceZapsignPutRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *SourceZapsignPutRequest) GetConfiguration() SourceZapsignUpdate {
	if o == nil {
		return SourceZapsignUpdate{}
	}
	return o.Configuration
}
