// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

type SourceReferralheroSourceType string

const (
	SourceReferralheroSourceTypeReferralhero SourceReferralheroSourceType = "referralhero"
)

func (e SourceReferralheroSourceType) ToPointer() *SourceReferralheroSourceType {
	return &e
}
func (e *SourceReferralheroSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "referralhero":
		*e = SourceReferralheroSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceReferralheroSourceType: %v", v)
	}
}

type SourceReferralhero struct {
	APIKey               string                        `json:"api_key"`
	sourceType           *SourceReferralheroSourceType `const:"referralhero" json:"sourceType"`
	AdditionalProperties any                           `additionalProperties:"true" json:"-"`
}

func (s SourceReferralhero) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceReferralhero) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceReferralhero) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}

func (s *SourceReferralhero) GetSourceType() *SourceReferralheroSourceType {
	return SourceReferralheroSourceTypeReferralhero.ToPointer()
}

func (s *SourceReferralhero) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
