// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceCaptainDataUpdate struct {
	// Your Captain Data project API key.
	APIKey string `json:"api_key"`
	// Your Captain Data project uuid.
	ProjectUID string `json:"project_uid"`
}

func (o *SourceCaptainDataUpdate) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *SourceCaptainDataUpdate) GetProjectUID() string {
	if o == nil {
		return ""
	}
	return o.ProjectUID
}
