// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

type SourceMicrosoftDataverseUpdateSourceType string

const (
	SourceMicrosoftDataverseUpdateSourceTypeMicrosoftDataverse SourceMicrosoftDataverseUpdateSourceType = "microsoft-dataverse"
)

func (e SourceMicrosoftDataverseUpdateSourceType) ToPointer() *SourceMicrosoftDataverseUpdateSourceType {
	return &e
}
func (e *SourceMicrosoftDataverseUpdateSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "microsoft-dataverse":
		*e = SourceMicrosoftDataverseUpdateSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceMicrosoftDataverseUpdateSourceType: %v", v)
	}
}

type SourceMicrosoftDataverseUpdate struct {
	// App Registration Client Id
	ClientID *string `json:"client_id,omitempty"`
	// App Registration Client Secret
	ClientSecretValue *string `json:"client_secret_value,omitempty"`
	// Max number of results per page. Default=5000
	OdataMaxpagesize *int64 `default:"5000" json:"odata_maxpagesize"`
	// Tenant Id of your Microsoft Dataverse Instance
	TenantID *string `json:"tenant_id,omitempty"`
	// URL to Microsoft Dataverse API
	URL                  *string                                   `json:"url,omitempty"`
	sourceType           *SourceMicrosoftDataverseUpdateSourceType `const:"microsoft-dataverse" json:"sourceType"`
	AdditionalProperties any                                       `additionalProperties:"true" json:"-"`
}

func (s SourceMicrosoftDataverseUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceMicrosoftDataverseUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceMicrosoftDataverseUpdate) GetClientID() *string {
	if s == nil {
		return nil
	}
	return s.ClientID
}

func (s *SourceMicrosoftDataverseUpdate) GetClientSecretValue() *string {
	if s == nil {
		return nil
	}
	return s.ClientSecretValue
}

func (s *SourceMicrosoftDataverseUpdate) GetOdataMaxpagesize() *int64 {
	if s == nil {
		return nil
	}
	return s.OdataMaxpagesize
}

func (s *SourceMicrosoftDataverseUpdate) GetTenantID() *string {
	if s == nil {
		return nil
	}
	return s.TenantID
}

func (s *SourceMicrosoftDataverseUpdate) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *SourceMicrosoftDataverseUpdate) GetSourceType() *SourceMicrosoftDataverseUpdateSourceType {
	return SourceMicrosoftDataverseUpdateSourceTypeMicrosoftDataverse.ToPointer()
}

func (s *SourceMicrosoftDataverseUpdate) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
