// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
	"time"
)

type Buildkite string

const (
	BuildkiteBuildkite Buildkite = "buildkite"
)

func (e Buildkite) ToPointer() *Buildkite {
	return &e
}
func (e *Buildkite) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "buildkite":
		*e = Buildkite(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Buildkite: %v", v)
	}
}

type SourceBuildkite struct {
	APIKey     string    `json:"api_key"`
	sourceType Buildkite `const:"buildkite" json:"sourceType"`
	StartDate  time.Time `json:"start_date"`
}

func (s SourceBuildkite) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceBuildkite) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SourceBuildkite) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *SourceBuildkite) GetSourceType() Buildkite {
	return BuildkiteBuildkite
}

func (o *SourceBuildkite) GetStartDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartDate
}
