// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/internal/utils"
)

// SourceDatadogUpdateDataSource - A data source that is powered by the platform.
type SourceDatadogUpdateDataSource string

const (
	SourceDatadogUpdateDataSourceMetrics   SourceDatadogUpdateDataSource = "metrics"
	SourceDatadogUpdateDataSourceCloudCost SourceDatadogUpdateDataSource = "cloud_cost"
	SourceDatadogUpdateDataSourceLogs      SourceDatadogUpdateDataSource = "logs"
	SourceDatadogUpdateDataSourceRum       SourceDatadogUpdateDataSource = "rum"
)

func (e SourceDatadogUpdateDataSource) ToPointer() *SourceDatadogUpdateDataSource {
	return &e
}
func (e *SourceDatadogUpdateDataSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "metrics":
		fallthrough
	case "cloud_cost":
		fallthrough
	case "logs":
		fallthrough
	case "rum":
		*e = SourceDatadogUpdateDataSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceDatadogUpdateDataSource: %v", v)
	}
}

type SourceDatadogUpdateQueries struct {
	// A data source that is powered by the platform.
	DataSource *SourceDatadogUpdateDataSource `json:"data_source,omitempty"`
	// The variable name for use in queries.
	Name *string `json:"name,omitempty"`
	// A classic query string.
	Query *string `json:"query,omitempty"`
}

func (s *SourceDatadogUpdateQueries) GetDataSource() *SourceDatadogUpdateDataSource {
	if s == nil {
		return nil
	}
	return s.DataSource
}

func (s *SourceDatadogUpdateQueries) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SourceDatadogUpdateQueries) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}

// SourceDatadogUpdateSite - The site where Datadog data resides in.
type SourceDatadogUpdateSite string

const (
	SourceDatadogUpdateSiteDatadoghqCom    SourceDatadogUpdateSite = "datadoghq.com"
	SourceDatadogUpdateSiteUs3DatadoghqCom SourceDatadogUpdateSite = "us3.datadoghq.com"
	SourceDatadogUpdateSiteUs5DatadoghqCom SourceDatadogUpdateSite = "us5.datadoghq.com"
	SourceDatadogUpdateSiteDatadoghqEu     SourceDatadogUpdateSite = "datadoghq.eu"
	SourceDatadogUpdateSiteDdogGovCom      SourceDatadogUpdateSite = "ddog-gov.com"
)

func (e SourceDatadogUpdateSite) ToPointer() *SourceDatadogUpdateSite {
	return &e
}
func (e *SourceDatadogUpdateSite) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "datadoghq.com":
		fallthrough
	case "us3.datadoghq.com":
		fallthrough
	case "us5.datadoghq.com":
		fallthrough
	case "datadoghq.eu":
		fallthrough
	case "ddog-gov.com":
		*e = SourceDatadogUpdateSite(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceDatadogUpdateSite: %v", v)
	}
}

type SourceDatadogUpdateSourceType string

const (
	SourceDatadogUpdateSourceTypeDatadog SourceDatadogUpdateSourceType = "datadog"
)

func (e SourceDatadogUpdateSourceType) ToPointer() *SourceDatadogUpdateSourceType {
	return &e
}
func (e *SourceDatadogUpdateSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "datadog":
		*e = SourceDatadogUpdateSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceDatadogUpdateSourceType: %v", v)
	}
}

type SourceDatadogUpdate struct {
	// Datadog API key
	APIKey *string `json:"api_key,omitempty"`
	// Datadog application key
	ApplicationKey *string `json:"application_key,omitempty"`
	// UTC date and time in the format 2017-01-25T00:00:00Z. Data after this date will  not be replicated. An empty value will represent the current datetime for each  execution. This just applies to Incremental syncs.
	EndDate *string `json:"end_date,omitempty"`
	// Maximum number of records to collect per request.
	MaxRecordsPerRequest *int64 `default:"5000" json:"max_records_per_request"`
	// List of queries to be run and used as inputs.
	Queries []SourceDatadogUpdateQueries `json:"queries,omitempty"`
	// The search query. This just applies to Incremental syncs. If empty, it'll collect all logs.
	Query *string `json:"query,omitempty"`
	// The site where Datadog data resides in.
	Site *SourceDatadogUpdateSite `default:"datadoghq.com" json:"site"`
	// UTC date and time in the format 2017-01-25T00:00:00Z. Any data before this date will not be replicated. This just applies to Incremental syncs.
	StartDate            *string                        `default:"2023-12-01T00:00:00Z" json:"start_date"`
	sourceType           *SourceDatadogUpdateSourceType `const:"datadog" json:"sourceType"`
	AdditionalProperties any                            `additionalProperties:"true" json:"-"`
}

func (s SourceDatadogUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceDatadogUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SourceDatadogUpdate) GetAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.APIKey
}

func (s *SourceDatadogUpdate) GetApplicationKey() *string {
	if s == nil {
		return nil
	}
	return s.ApplicationKey
}

func (s *SourceDatadogUpdate) GetEndDate() *string {
	if s == nil {
		return nil
	}
	return s.EndDate
}

func (s *SourceDatadogUpdate) GetMaxRecordsPerRequest() *int64 {
	if s == nil {
		return nil
	}
	return s.MaxRecordsPerRequest
}

func (s *SourceDatadogUpdate) GetQueries() []SourceDatadogUpdateQueries {
	if s == nil {
		return nil
	}
	return s.Queries
}

func (s *SourceDatadogUpdate) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}

func (s *SourceDatadogUpdate) GetSite() *SourceDatadogUpdateSite {
	if s == nil {
		return nil
	}
	return s.Site
}

func (s *SourceDatadogUpdate) GetStartDate() *string {
	if s == nil {
		return nil
	}
	return s.StartDate
}

func (s *SourceDatadogUpdate) GetSourceType() *SourceDatadogUpdateSourceType {
	return SourceDatadogUpdateSourceTypeDatadog.ToPointer()
}

func (s *SourceDatadogUpdate) GetAdditionalProperties() any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}
