// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceApptivoPutRequest struct {
	Name          string              `json:"name"`
	WorkspaceID   string              `json:"workspaceId"`
	Configuration SourceApptivoUpdate `json:"configuration"`
}

func (o *SourceApptivoPutRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SourceApptivoPutRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *SourceApptivoPutRequest) GetConfiguration() SourceApptivoUpdate {
	if o == nil {
		return SourceApptivoUpdate{}
	}
	return o.Configuration
}
