// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceSendgridCreateRequest struct {
	// Name of the source e.g. dev-mysql-instance.
	Name string `json:"name"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided.
	DefinitionID  *string        `json:"definitionId,omitempty"`
	WorkspaceID   string         `json:"workspaceId"`
	Configuration SourceSendgrid `json:"configuration"`
	// Optional secretID obtained through the public API OAuth redirect flow.
	SecretID *string `json:"secretId,omitempty"`
}

func (s *SourceSendgridCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceSendgridCreateRequest) GetDefinitionID() *string {
	if s == nil {
		return nil
	}
	return s.DefinitionID
}

func (s *SourceSendgridCreateRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *SourceSendgridCreateRequest) GetConfiguration() SourceSendgrid {
	if s == nil {
		return SourceSendgrid{}
	}
	return s.Configuration
}

func (s *SourceSendgridCreateRequest) GetSecretID() *string {
	if s == nil {
		return nil
	}
	return s.SecretID
}
