// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SourceOrbPutRequest struct {
	Name          string          `json:"name"`
	WorkspaceID   string          `json:"workspaceId"`
	Configuration SourceOrbUpdate `json:"configuration"`
}

func (o *SourceOrbPutRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SourceOrbPutRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *SourceOrbPutRequest) GetConfiguration() SourceOrbUpdate {
	if o == nil {
		return SourceOrbUpdate{}
	}
	return o.Configuration
}
