// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WorkspacesResponse struct {
	Previous *string             `json:"previous,omitempty"`
	Next     *string             `json:"next,omitempty"`
	Data     []WorkspaceResponse `json:"data"`
}

func (o *WorkspacesResponse) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *WorkspacesResponse) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *WorkspacesResponse) GetData() []WorkspaceResponse {
	if o == nil {
		return []WorkspaceResponse{}
	}
	return o.Data
}
