workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: ./generated/api_terraform.yaml
        registry:
            location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source
targets:
    terraform-provider-airbyte:
        target: terraform
        source: my-source
