workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/airbytehq/airbyte-platform/refs/heads/main/airbyte-api/server-api/src/main/openapi/api_terraform.yaml
        registry:
            location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source
targets:
    terraform-provider-airbyte:
        target: terraform
        source: my-source
