// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DestinationCumulioDataSourceModel) RefreshFromGetResponse(resp *shared.DestinationCumulioGetResponse) {
	r.Configuration.APIHost = types.StringValue(resp.Configuration.APIHost)
	r.Configuration.APIKey = types.StringValue(resp.Configuration.APIKey)
	r.Configuration.APIToken = types.StringValue(resp.Configuration.APIToken)
	r.Configuration.DestinationType = types.StringValue(string(resp.Configuration.DestinationType))
	if resp.DestinationID != nil {
		r.DestinationID = types.StringValue(*resp.DestinationID)
	} else {
		r.DestinationID = types.StringNull()
	}
	r.Name = types.StringValue(resp.Name)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)
}
