// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *SourceOnesignalResourceModel) ToCreateSDKType() *shared.SourceOnesignalCreateRequest {
	var applications []shared.SourceOnesignalApplications = nil
	for _, applicationsItem := range r.Configuration.Applications {
		appAPIKey := applicationsItem.AppAPIKey.ValueString()
		appID := applicationsItem.AppID.ValueString()
		appName := new(string)
		if !applicationsItem.AppName.IsUnknown() && !applicationsItem.AppName.IsNull() {
			*appName = applicationsItem.AppName.ValueString()
		} else {
			appName = nil
		}
		applications = append(applications, shared.SourceOnesignalApplications{
			AppAPIKey: appAPIKey,
			AppID:     appID,
			AppName:   appName,
		})
	}
	outcomeNames := r.Configuration.OutcomeNames.ValueString()
	sourceType := shared.SourceOnesignalOnesignal(r.Configuration.SourceType.ValueString())
	startDate, _ := time.Parse(time.RFC3339Nano, r.Configuration.StartDate.ValueString())
	userAuthKey := r.Configuration.UserAuthKey.ValueString()
	configuration := shared.SourceOnesignal{
		Applications: applications,
		OutcomeNames: outcomeNames,
		SourceType:   sourceType,
		StartDate:    startDate,
		UserAuthKey:  userAuthKey,
	}
	name := r.Name.ValueString()
	secretID := new(string)
	if !r.SecretID.IsUnknown() && !r.SecretID.IsNull() {
		*secretID = r.SecretID.ValueString()
	} else {
		secretID = nil
	}
	workspaceID := r.WorkspaceID.ValueString()
	out := shared.SourceOnesignalCreateRequest{
		Configuration: configuration,
		Name:          name,
		SecretID:      secretID,
		WorkspaceID:   workspaceID,
	}
	return &out
}

func (r *SourceOnesignalResourceModel) ToGetSDKType() *shared.SourceOnesignalCreateRequest {
	out := r.ToCreateSDKType()
	return out
}

func (r *SourceOnesignalResourceModel) ToUpdateSDKType() *shared.SourceOnesignalPutRequest {
	var applications []shared.SourceOnesignalUpdateApplications = nil
	for _, applicationsItem := range r.Configuration.Applications {
		appAPIKey := applicationsItem.AppAPIKey.ValueString()
		appID := applicationsItem.AppID.ValueString()
		appName := new(string)
		if !applicationsItem.AppName.IsUnknown() && !applicationsItem.AppName.IsNull() {
			*appName = applicationsItem.AppName.ValueString()
		} else {
			appName = nil
		}
		applications = append(applications, shared.SourceOnesignalUpdateApplications{
			AppAPIKey: appAPIKey,
			AppID:     appID,
			AppName:   appName,
		})
	}
	outcomeNames := r.Configuration.OutcomeNames.ValueString()
	startDate, _ := time.Parse(time.RFC3339Nano, r.Configuration.StartDate.ValueString())
	userAuthKey := r.Configuration.UserAuthKey.ValueString()
	configuration := shared.SourceOnesignalUpdate{
		Applications: applications,
		OutcomeNames: outcomeNames,
		StartDate:    startDate,
		UserAuthKey:  userAuthKey,
	}
	name := r.Name.ValueString()
	workspaceID := r.WorkspaceID.ValueString()
	out := shared.SourceOnesignalPutRequest{
		Configuration: configuration,
		Name:          name,
		WorkspaceID:   workspaceID,
	}
	return &out
}

func (r *SourceOnesignalResourceModel) ToDeleteSDKType() *shared.SourceOnesignalCreateRequest {
	out := r.ToCreateSDKType()
	return out
}

func (r *SourceOnesignalResourceModel) RefreshFromGetResponse(resp *shared.SourceOnesignalGetResponse) {
	r.Configuration.Applications = nil
	for _, applicationsItem := range resp.Configuration.Applications {
		var applications1 SourceOnesignalApplications
		applications1.AppAPIKey = types.StringValue(applicationsItem.AppAPIKey)
		applications1.AppID = types.StringValue(applicationsItem.AppID)
		if applicationsItem.AppName != nil {
			applications1.AppName = types.StringValue(*applicationsItem.AppName)
		} else {
			applications1.AppName = types.StringNull()
		}
		r.Configuration.Applications = append(r.Configuration.Applications, applications1)
	}
	r.Configuration.OutcomeNames = types.StringValue(resp.Configuration.OutcomeNames)
	r.Configuration.SourceType = types.StringValue(string(resp.Configuration.SourceType))
	r.Configuration.StartDate = types.StringValue(resp.Configuration.StartDate.Format(time.RFC3339))
	r.Configuration.UserAuthKey = types.StringValue(resp.Configuration.UserAuthKey)
	r.Name = types.StringValue(resp.Name)
	if resp.SecretID != nil {
		r.SecretID = types.StringValue(*resp.SecretID)
	} else {
		r.SecretID = types.StringNull()
	}
	if resp.SourceID != nil {
		r.SourceID = types.StringValue(*resp.SourceID)
	} else {
		r.SourceID = types.StringNull()
	}
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)
}

func (r *SourceOnesignalResourceModel) RefreshFromCreateResponse(resp *shared.SourceOnesignalGetResponse) {
	r.RefreshFromGetResponse(resp)
}
