// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *SourceSalesforceResourceModel) ToCreateSDKType() *shared.SourceSalesforceCreateRequest {
	authType := new(shared.SourceSalesforceAuthType)
	if !r.Configuration.AuthType.IsUnknown() && !r.Configuration.AuthType.IsNull() {
		*authType = shared.SourceSalesforceAuthType(r.Configuration.AuthType.ValueString())
	} else {
		authType = nil
	}
	clientID := r.Configuration.ClientID.ValueString()
	clientSecret := r.Configuration.ClientSecret.ValueString()
	forceUseBulkAPI := new(bool)
	if !r.Configuration.ForceUseBulkAPI.IsUnknown() && !r.Configuration.ForceUseBulkAPI.IsNull() {
		*forceUseBulkAPI = r.Configuration.ForceUseBulkAPI.ValueBool()
	} else {
		forceUseBulkAPI = nil
	}
	isSandbox := new(bool)
	if !r.Configuration.IsSandbox.IsUnknown() && !r.Configuration.IsSandbox.IsNull() {
		*isSandbox = r.Configuration.IsSandbox.ValueBool()
	} else {
		isSandbox = nil
	}
	refreshToken := r.Configuration.RefreshToken.ValueString()
	sourceType := shared.SourceSalesforceSalesforce(r.Configuration.SourceType.ValueString())
	startDate := new(time.Time)
	if !r.Configuration.StartDate.IsUnknown() && !r.Configuration.StartDate.IsNull() {
		*startDate, _ = time.Parse(time.RFC3339Nano, r.Configuration.StartDate.ValueString())
	} else {
		startDate = nil
	}
	var streamsCriteria []shared.SourceSalesforceStreamsCriteria = nil
	for _, streamsCriteriaItem := range r.Configuration.StreamsCriteria {
		criteria := shared.SourceSalesforceStreamsCriteriaSearchCriteria(streamsCriteriaItem.Criteria.ValueString())
		value := streamsCriteriaItem.Value.ValueString()
		streamsCriteria = append(streamsCriteria, shared.SourceSalesforceStreamsCriteria{
			Criteria: criteria,
			Value:    value,
		})
	}
	configuration := shared.SourceSalesforce{
		AuthType:        authType,
		ClientID:        clientID,
		ClientSecret:    clientSecret,
		ForceUseBulkAPI: forceUseBulkAPI,
		IsSandbox:       isSandbox,
		RefreshToken:    refreshToken,
		SourceType:      sourceType,
		StartDate:       startDate,
		StreamsCriteria: streamsCriteria,
	}
	name := r.Name.ValueString()
	secretID := new(string)
	if !r.SecretID.IsUnknown() && !r.SecretID.IsNull() {
		*secretID = r.SecretID.ValueString()
	} else {
		secretID = nil
	}
	workspaceID := r.WorkspaceID.ValueString()
	out := shared.SourceSalesforceCreateRequest{
		Configuration: configuration,
		Name:          name,
		SecretID:      secretID,
		WorkspaceID:   workspaceID,
	}
	return &out
}

func (r *SourceSalesforceResourceModel) ToGetSDKType() *shared.SourceSalesforceCreateRequest {
	out := r.ToCreateSDKType()
	return out
}

func (r *SourceSalesforceResourceModel) ToUpdateSDKType() *shared.SourceSalesforcePutRequest {
	authType := new(shared.SourceSalesforceUpdateAuthType)
	if !r.Configuration.AuthType.IsUnknown() && !r.Configuration.AuthType.IsNull() {
		*authType = shared.SourceSalesforceUpdateAuthType(r.Configuration.AuthType.ValueString())
	} else {
		authType = nil
	}
	clientID := r.Configuration.ClientID.ValueString()
	clientSecret := r.Configuration.ClientSecret.ValueString()
	forceUseBulkAPI := new(bool)
	if !r.Configuration.ForceUseBulkAPI.IsUnknown() && !r.Configuration.ForceUseBulkAPI.IsNull() {
		*forceUseBulkAPI = r.Configuration.ForceUseBulkAPI.ValueBool()
	} else {
		forceUseBulkAPI = nil
	}
	isSandbox := new(bool)
	if !r.Configuration.IsSandbox.IsUnknown() && !r.Configuration.IsSandbox.IsNull() {
		*isSandbox = r.Configuration.IsSandbox.ValueBool()
	} else {
		isSandbox = nil
	}
	refreshToken := r.Configuration.RefreshToken.ValueString()
	startDate := new(time.Time)
	if !r.Configuration.StartDate.IsUnknown() && !r.Configuration.StartDate.IsNull() {
		*startDate, _ = time.Parse(time.RFC3339Nano, r.Configuration.StartDate.ValueString())
	} else {
		startDate = nil
	}
	var streamsCriteria []shared.SourceSalesforceUpdateStreamsCriteria = nil
	for _, streamsCriteriaItem := range r.Configuration.StreamsCriteria {
		criteria := shared.SourceSalesforceUpdateStreamsCriteriaSearchCriteria(streamsCriteriaItem.Criteria.ValueString())
		value := streamsCriteriaItem.Value.ValueString()
		streamsCriteria = append(streamsCriteria, shared.SourceSalesforceUpdateStreamsCriteria{
			Criteria: criteria,
			Value:    value,
		})
	}
	configuration := shared.SourceSalesforceUpdate{
		AuthType:        authType,
		ClientID:        clientID,
		ClientSecret:    clientSecret,
		ForceUseBulkAPI: forceUseBulkAPI,
		IsSandbox:       isSandbox,
		RefreshToken:    refreshToken,
		StartDate:       startDate,
		StreamsCriteria: streamsCriteria,
	}
	name := r.Name.ValueString()
	workspaceID := r.WorkspaceID.ValueString()
	out := shared.SourceSalesforcePutRequest{
		Configuration: configuration,
		Name:          name,
		WorkspaceID:   workspaceID,
	}
	return &out
}

func (r *SourceSalesforceResourceModel) ToDeleteSDKType() *shared.SourceSalesforceCreateRequest {
	out := r.ToCreateSDKType()
	return out
}

func (r *SourceSalesforceResourceModel) RefreshFromGetResponse(resp *shared.SourceSalesforceGetResponse) {
	if resp.Configuration.AuthType != nil {
		r.Configuration.AuthType = types.StringValue(string(*resp.Configuration.AuthType))
	} else {
		r.Configuration.AuthType = types.StringNull()
	}
	r.Configuration.ClientID = types.StringValue(resp.Configuration.ClientID)
	r.Configuration.ClientSecret = types.StringValue(resp.Configuration.ClientSecret)
	if resp.Configuration.ForceUseBulkAPI != nil {
		r.Configuration.ForceUseBulkAPI = types.BoolValue(*resp.Configuration.ForceUseBulkAPI)
	} else {
		r.Configuration.ForceUseBulkAPI = types.BoolNull()
	}
	if resp.Configuration.IsSandbox != nil {
		r.Configuration.IsSandbox = types.BoolValue(*resp.Configuration.IsSandbox)
	} else {
		r.Configuration.IsSandbox = types.BoolNull()
	}
	r.Configuration.RefreshToken = types.StringValue(resp.Configuration.RefreshToken)
	r.Configuration.SourceType = types.StringValue(string(resp.Configuration.SourceType))
	if resp.Configuration.StartDate != nil {
		r.Configuration.StartDate = types.StringValue(resp.Configuration.StartDate.Format(time.RFC3339))
	} else {
		r.Configuration.StartDate = types.StringNull()
	}
	r.Configuration.StreamsCriteria = nil
	for _, streamsCriteriaItem := range resp.Configuration.StreamsCriteria {
		var streamsCriteria1 SourceSalesforceStreamsCriteria
		streamsCriteria1.Criteria = types.StringValue(string(streamsCriteriaItem.Criteria))
		streamsCriteria1.Value = types.StringValue(streamsCriteriaItem.Value)
		r.Configuration.StreamsCriteria = append(r.Configuration.StreamsCriteria, streamsCriteria1)
	}
	r.Name = types.StringValue(resp.Name)
	if resp.SecretID != nil {
		r.SecretID = types.StringValue(*resp.SecretID)
	} else {
		r.SecretID = types.StringNull()
	}
	if resp.SourceID != nil {
		r.SourceID = types.StringValue(*resp.SourceID)
	} else {
		r.SourceID = types.StringNull()
	}
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)
}

func (r *SourceSalesforceResourceModel) RefreshFromCreateResponse(resp *shared.SourceSalesforceGetResponse) {
	r.RefreshFromGetResponse(resp)
}
