// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	tfTypes "github.com/airbytehq/terraform-provider-airbyte/internal/provider/types"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/operations"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SourceCoassembleResourceModel) RefreshFromSharedSourceResponse(ctx context.Context, resp *shared.SourceResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		configurationPriorData := r.Configuration
		r.Configuration.AdditionalProperties = configurationPriorData.AdditionalProperties
		r.Configuration.UserID = configurationPriorData.UserID
		r.Configuration.UserToken = configurationPriorData.UserToken
		r.CreatedAt = types.Int64Value(resp.CreatedAt)
		r.DefinitionID = types.StringValue(resp.DefinitionID)
		r.Name = types.StringValue(resp.Name)
		if resp.ResourceAllocation == nil {
			r.ResourceAllocation = nil
		} else {
			r.ResourceAllocation = &tfTypes.ScopedResourceRequirements{}
			if resp.ResourceAllocation.Default == nil {
				r.ResourceAllocation.Default = nil
			} else {
				r.ResourceAllocation.Default = &tfTypes.ResourceRequirements{}
				r.ResourceAllocation.Default.CPULimit = types.StringPointerValue(resp.ResourceAllocation.Default.CPULimit)
				r.ResourceAllocation.Default.CPURequest = types.StringPointerValue(resp.ResourceAllocation.Default.CPURequest)
				r.ResourceAllocation.Default.EphemeralStorageLimit = types.StringPointerValue(resp.ResourceAllocation.Default.EphemeralStorageLimit)
				r.ResourceAllocation.Default.EphemeralStorageRequest = types.StringPointerValue(resp.ResourceAllocation.Default.EphemeralStorageRequest)
				r.ResourceAllocation.Default.MemoryLimit = types.StringPointerValue(resp.ResourceAllocation.Default.MemoryLimit)
				r.ResourceAllocation.Default.MemoryRequest = types.StringPointerValue(resp.ResourceAllocation.Default.MemoryRequest)
			}
			r.ResourceAllocation.JobSpecific = []tfTypes.JobTypeResourceLimit{}

			for _, jobSpecificItem := range resp.ResourceAllocation.JobSpecific {
				var jobSpecific tfTypes.JobTypeResourceLimit

				jobSpecific.JobType = types.StringValue(string(jobSpecificItem.JobType))
				jobSpecific.ResourceRequirements.CPULimit = types.StringPointerValue(jobSpecificItem.ResourceRequirements.CPULimit)
				jobSpecific.ResourceRequirements.CPURequest = types.StringPointerValue(jobSpecificItem.ResourceRequirements.CPURequest)
				jobSpecific.ResourceRequirements.EphemeralStorageLimit = types.StringPointerValue(jobSpecificItem.ResourceRequirements.EphemeralStorageLimit)
				jobSpecific.ResourceRequirements.EphemeralStorageRequest = types.StringPointerValue(jobSpecificItem.ResourceRequirements.EphemeralStorageRequest)
				jobSpecific.ResourceRequirements.MemoryLimit = types.StringPointerValue(jobSpecificItem.ResourceRequirements.MemoryLimit)
				jobSpecific.ResourceRequirements.MemoryRequest = types.StringPointerValue(jobSpecificItem.ResourceRequirements.MemoryRequest)

				r.ResourceAllocation.JobSpecific = append(r.ResourceAllocation.JobSpecific, jobSpecific)
			}
		}
		r.SourceID = types.StringValue(resp.SourceID)
		r.SourceType = types.StringValue(resp.SourceType)
		r.WorkspaceID = types.StringValue(resp.WorkspaceID)
	}

	return diags
}

func (r *SourceCoassembleResourceModel) ToOperationsDeleteSourceCoassembleRequest(ctx context.Context) (*operations.DeleteSourceCoassembleRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceID string
	sourceID = r.SourceID.ValueString()

	out := operations.DeleteSourceCoassembleRequest{
		SourceID: sourceID,
	}

	return &out, diags
}

func (r *SourceCoassembleResourceModel) ToOperationsGetSourceCoassembleRequest(ctx context.Context) (*operations.GetSourceCoassembleRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceID string
	sourceID = r.SourceID.ValueString()

	out := operations.GetSourceCoassembleRequest{
		SourceID: sourceID,
	}

	return &out, diags
}

func (r *SourceCoassembleResourceModel) ToOperationsPutSourceCoassembleRequest(ctx context.Context) (*operations.PutSourceCoassembleRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceID string
	sourceID = r.SourceID.ValueString()

	sourceCoassemblePutRequest, sourceCoassemblePutRequestDiags := r.ToSharedSourceCoassemblePutRequest(ctx)
	diags.Append(sourceCoassemblePutRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutSourceCoassembleRequest{
		SourceID:                   sourceID,
		SourceCoassemblePutRequest: *sourceCoassemblePutRequest,
	}

	return &out, diags
}

func (r *SourceCoassembleResourceModel) ToSharedSourceCoassembleCreateRequest(ctx context.Context) (*shared.SourceCoassembleCreateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	definitionID := new(string)
	if !r.DefinitionID.IsUnknown() && !r.DefinitionID.IsNull() {
		*definitionID = r.DefinitionID.ValueString()
	} else {
		definitionID = nil
	}
	var workspaceID string
	workspaceID = r.WorkspaceID.ValueString()

	var userID string
	userID = r.Configuration.UserID.ValueString()

	var userToken string
	userToken = r.Configuration.UserToken.ValueString()

	var additionalProperties map[string]any
	if !r.Configuration.AdditionalProperties.IsUnknown() && !r.Configuration.AdditionalProperties.IsNull() {
		_ = json.Unmarshal([]byte(r.Configuration.AdditionalProperties.ValueString()), &additionalProperties)
	}
	configuration := shared.SourceCoassemble{
		UserID:               userID,
		UserToken:            userToken,
		AdditionalProperties: additionalProperties,
	}
	secretID := new(string)
	if !r.SecretID.IsUnknown() && !r.SecretID.IsNull() {
		*secretID = r.SecretID.ValueString()
	} else {
		secretID = nil
	}
	out := shared.SourceCoassembleCreateRequest{
		Name:          name,
		DefinitionID:  definitionID,
		WorkspaceID:   workspaceID,
		Configuration: configuration,
		SecretID:      secretID,
	}

	return &out, diags
}

func (r *SourceCoassembleResourceModel) ToSharedSourceCoassemblePutRequest(ctx context.Context) (*shared.SourceCoassemblePutRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	var workspaceID string
	workspaceID = r.WorkspaceID.ValueString()

	userID := new(string)
	if !r.Configuration.UserID.IsUnknown() && !r.Configuration.UserID.IsNull() {
		*userID = r.Configuration.UserID.ValueString()
	} else {
		userID = nil
	}
	userToken := new(string)
	if !r.Configuration.UserToken.IsUnknown() && !r.Configuration.UserToken.IsNull() {
		*userToken = r.Configuration.UserToken.ValueString()
	} else {
		userToken = nil
	}
	var additionalProperties map[string]any
	if !r.Configuration.AdditionalProperties.IsUnknown() && !r.Configuration.AdditionalProperties.IsNull() {
		_ = json.Unmarshal([]byte(r.Configuration.AdditionalProperties.ValueString()), &additionalProperties)
	}
	configuration := shared.SourceCoassembleUpdate{
		UserID:               userID,
		UserToken:            userToken,
		AdditionalProperties: additionalProperties,
	}
	out := shared.SourceCoassemblePutRequest{
		Name:          name,
		WorkspaceID:   workspaceID,
		Configuration: configuration,
	}

	return &out, diags
}
