// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"airbyte/internal/sdk/pkg/models/shared"
)

func (r *SourceFacebookPagesResourceModel) ToCreateSDKType() *shared.SourceFacebookPagesCreateRequest {
	accessToken := r.Configuration.AccessToken.ValueString()
	pageID := r.Configuration.PageID.ValueString()
	sourceType := shared.SourceFacebookPagesFacebookPagesEnum(r.Configuration.SourceType.ValueString())
	configuration := shared.SourceFacebookPages{
		AccessToken: accessToken,
		PageID:      pageID,
		SourceType:  sourceType,
	}
	name := r.Name.ValueString()
	secretID := new(string)
	if !r.SecretID.IsUnknown() && !r.SecretID.IsNull() {
		*secretID = r.SecretID.ValueString()
	} else {
		secretID = nil
	}
	workspaceID := r.WorkspaceID.ValueString()
	out := shared.SourceFacebookPagesCreateRequest{
		Configuration: configuration,
		Name:          name,
		SecretID:      secretID,
		WorkspaceID:   workspaceID,
	}
	return &out
}

func (r *SourceFacebookPagesResourceModel) ToDeleteSDKType() *shared.SourceFacebookPagesCreateRequest {
	out := r.ToCreateSDKType()
	return out
}
