// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	tfTypes "github.com/airbytehq/terraform-provider-airbyte/internal/provider/types"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/operations"
	"github.com/airbytehq/terraform-provider-airbyte/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *SourceTrelloResourceModel) RefreshFromSharedSourceResponse(ctx context.Context, resp *shared.SourceResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		configurationPriorData := r.Configuration
		r.Configuration = &tfTypes.SourceTrello{}
		if configurationPriorData != nil {
			r.Configuration.AdditionalProperties = configurationPriorData.AdditionalProperties
			r.Configuration.BoardIds = configurationPriorData.BoardIds
			r.Configuration.Key = configurationPriorData.Key
			r.Configuration.StartDate = configurationPriorData.StartDate
			r.Configuration.Token = configurationPriorData.Token
		}
		r.CreatedAt = types.Int64Value(resp.CreatedAt)
		r.DefinitionID = types.StringValue(resp.DefinitionID)
		r.Name = types.StringValue(resp.Name)
		if resp.ResourceAllocation == nil {
			r.ResourceAllocation = nil
		} else {
			r.ResourceAllocation = &tfTypes.ScopedResourceRequirements{}
			if resp.ResourceAllocation.Default == nil {
				r.ResourceAllocation.Default = nil
			} else {
				r.ResourceAllocation.Default = &tfTypes.ResourceRequirements{}
				r.ResourceAllocation.Default.CPULimit = types.StringPointerValue(resp.ResourceAllocation.Default.CPULimit)
				r.ResourceAllocation.Default.CPURequest = types.StringPointerValue(resp.ResourceAllocation.Default.CPURequest)
				r.ResourceAllocation.Default.EphemeralStorageLimit = types.StringPointerValue(resp.ResourceAllocation.Default.EphemeralStorageLimit)
				r.ResourceAllocation.Default.EphemeralStorageRequest = types.StringPointerValue(resp.ResourceAllocation.Default.EphemeralStorageRequest)
				r.ResourceAllocation.Default.MemoryLimit = types.StringPointerValue(resp.ResourceAllocation.Default.MemoryLimit)
				r.ResourceAllocation.Default.MemoryRequest = types.StringPointerValue(resp.ResourceAllocation.Default.MemoryRequest)
			}
			r.ResourceAllocation.JobSpecific = []tfTypes.JobTypeResourceLimit{}

			for _, jobSpecificItem := range resp.ResourceAllocation.JobSpecific {
				var jobSpecific tfTypes.JobTypeResourceLimit

				jobSpecific.JobType = types.StringValue(string(jobSpecificItem.JobType))
				jobSpecific.ResourceRequirements = &tfTypes.ResourceRequirements{}
				jobSpecific.ResourceRequirements.CPULimit = types.StringPointerValue(jobSpecificItem.ResourceRequirements.CPULimit)
				jobSpecific.ResourceRequirements.CPURequest = types.StringPointerValue(jobSpecificItem.ResourceRequirements.CPURequest)
				jobSpecific.ResourceRequirements.EphemeralStorageLimit = types.StringPointerValue(jobSpecificItem.ResourceRequirements.EphemeralStorageLimit)
				jobSpecific.ResourceRequirements.EphemeralStorageRequest = types.StringPointerValue(jobSpecificItem.ResourceRequirements.EphemeralStorageRequest)
				jobSpecific.ResourceRequirements.MemoryLimit = types.StringPointerValue(jobSpecificItem.ResourceRequirements.MemoryLimit)
				jobSpecific.ResourceRequirements.MemoryRequest = types.StringPointerValue(jobSpecificItem.ResourceRequirements.MemoryRequest)

				r.ResourceAllocation.JobSpecific = append(r.ResourceAllocation.JobSpecific, jobSpecific)
			}
		}
		r.SourceID = types.StringValue(resp.SourceID)
		r.SourceType = types.StringValue(resp.SourceType)
		r.WorkspaceID = types.StringValue(resp.WorkspaceID)
	}

	return diags
}

func (r *SourceTrelloResourceModel) ToOperationsDeleteSourceTrelloRequest(ctx context.Context) (*operations.DeleteSourceTrelloRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceID string
	sourceID = r.SourceID.ValueString()

	out := operations.DeleteSourceTrelloRequest{
		SourceID: sourceID,
	}

	return &out, diags
}

func (r *SourceTrelloResourceModel) ToOperationsGetSourceTrelloRequest(ctx context.Context) (*operations.GetSourceTrelloRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceID string
	sourceID = r.SourceID.ValueString()

	out := operations.GetSourceTrelloRequest{
		SourceID: sourceID,
	}

	return &out, diags
}

func (r *SourceTrelloResourceModel) ToOperationsPutSourceTrelloRequest(ctx context.Context) (*operations.PutSourceTrelloRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceID string
	sourceID = r.SourceID.ValueString()

	sourceTrelloPutRequest, sourceTrelloPutRequestDiags := r.ToSharedSourceTrelloPutRequest(ctx)
	diags.Append(sourceTrelloPutRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutSourceTrelloRequest{
		SourceID:               sourceID,
		SourceTrelloPutRequest: *sourceTrelloPutRequest,
	}

	return &out, diags
}

func (r *SourceTrelloResourceModel) ToSharedSourceTrelloCreateRequest(ctx context.Context) (*shared.SourceTrelloCreateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	definitionID := new(string)
	if !r.DefinitionID.IsUnknown() && !r.DefinitionID.IsNull() {
		*definitionID = r.DefinitionID.ValueString()
	} else {
		definitionID = nil
	}
	var workspaceID string
	workspaceID = r.WorkspaceID.ValueString()

	boardIds := make([]string, 0, len(r.Configuration.BoardIds))
	for boardIdsIndex := range r.Configuration.BoardIds {
		boardIds = append(boardIds, r.Configuration.BoardIds[boardIdsIndex].ValueString())
	}
	var key string
	key = r.Configuration.Key.ValueString()

	startDate, _ := time.Parse(time.RFC3339Nano, r.Configuration.StartDate.ValueString())
	var token string
	token = r.Configuration.Token.ValueString()

	var additionalProperties map[string]any
	if !r.Configuration.AdditionalProperties.IsUnknown() && !r.Configuration.AdditionalProperties.IsNull() {
		_ = json.Unmarshal([]byte(r.Configuration.AdditionalProperties.ValueString()), &additionalProperties)
	}
	configuration := shared.SourceTrello{
		BoardIds:             boardIds,
		Key:                  key,
		StartDate:            startDate,
		Token:                token,
		AdditionalProperties: additionalProperties,
	}
	secretID := new(string)
	if !r.SecretID.IsUnknown() && !r.SecretID.IsNull() {
		*secretID = r.SecretID.ValueString()
	} else {
		secretID = nil
	}
	out := shared.SourceTrelloCreateRequest{
		Name:          name,
		DefinitionID:  definitionID,
		WorkspaceID:   workspaceID,
		Configuration: configuration,
		SecretID:      secretID,
	}

	return &out, diags
}

func (r *SourceTrelloResourceModel) ToSharedSourceTrelloPutRequest(ctx context.Context) (*shared.SourceTrelloPutRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	var workspaceID string
	workspaceID = r.WorkspaceID.ValueString()

	boardIds := make([]string, 0, len(r.Configuration.BoardIds))
	for boardIdsIndex := range r.Configuration.BoardIds {
		boardIds = append(boardIds, r.Configuration.BoardIds[boardIdsIndex].ValueString())
	}
	key := new(string)
	if !r.Configuration.Key.IsUnknown() && !r.Configuration.Key.IsNull() {
		*key = r.Configuration.Key.ValueString()
	} else {
		key = nil
	}
	startDate := new(time.Time)
	if !r.Configuration.StartDate.IsUnknown() && !r.Configuration.StartDate.IsNull() {
		*startDate, _ = time.Parse(time.RFC3339Nano, r.Configuration.StartDate.ValueString())
	} else {
		startDate = nil
	}
	token := new(string)
	if !r.Configuration.Token.IsUnknown() && !r.Configuration.Token.IsNull() {
		*token = r.Configuration.Token.ValueString()
	} else {
		token = nil
	}
	var additionalProperties map[string]any
	if !r.Configuration.AdditionalProperties.IsUnknown() && !r.Configuration.AdditionalProperties.IsNull() {
		_ = json.Unmarshal([]byte(r.Configuration.AdditionalProperties.ValueString()), &additionalProperties)
	}
	configuration := shared.SourceTrelloUpdate{
		BoardIds:             boardIds,
		Key:                  key,
		StartDate:            startDate,
		Token:                token,
		AdditionalProperties: additionalProperties,
	}
	out := shared.SourceTrelloPutRequest{
		Name:          name,
		WorkspaceID:   workspaceID,
		Configuration: configuration,
	}

	return &out, diags
}
