// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type SourceOracleSSHTunnelMethod struct {
	SourceOracleSSHTunnelMethodNoTunnel               *DestinationClickhouseSSHTunnelMethodNoTunnel               `tfsdk:"source_oracle_ssh_tunnel_method_no_tunnel"`
	SourceOracleSSHTunnelMethodSSHKeyAuthentication   *DestinationClickhouseSSHTunnelMethodSSHKeyAuthentication   `tfsdk:"source_oracle_ssh_tunnel_method_ssh_key_authentication"`
	SourceOracleSSHTunnelMethodPasswordAuthentication *DestinationClickhouseSSHTunnelMethodPasswordAuthentication `tfsdk:"source_oracle_ssh_tunnel_method_password_authentication"`
}
