// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type DestinationSnowflakeUpdateDataStagingMethodRecommendedInternalStaging struct {
	Method types.String `tfsdk:"method"`
}
