// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type DestinationFireboltLoadingMethod struct {
	DestinationFireboltLoadingMethodExternalTableViaS3       *DestinationFireboltLoadingMethodExternalTableViaS3                   `tfsdk:"destination_firebolt_loading_method_external_table_via_s3"`
	DestinationFireboltLoadingMethodSQLInserts               *DestinationAzureBlobStorageOutputFormatJSONLinesNewlineDelimitedJSON `tfsdk:"destination_firebolt_loading_method_sql_inserts"`
	DestinationFireboltUpdateLoadingMethodExternalTableViaS3 *DestinationFireboltLoadingMethodExternalTableViaS3                   `tfsdk:"destination_firebolt_update_loading_method_external_table_via_s3"`
	DestinationFireboltUpdateLoadingMethodSQLInserts         *DestinationAzureBlobStorageOutputFormatJSONLinesNewlineDelimitedJSON `tfsdk:"destination_firebolt_update_loading_method_sql_inserts"`
}
