// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type DestinationRedisSSLModes struct {
	Disable    *DestinationAzureBlobStorageJSONLinesNewlineDelimitedJSON `tfsdk:"disable"`
	VerifyFull *VerifyFull                                               `tfsdk:"verify_full"`
}
