// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type DestinationMilvusEmbedding struct {
	AzureOpenAI      *AzureOpenAI                                              `tfsdk:"azure_open_ai"`
	Cohere           *Cohere                                                   `tfsdk:"cohere"`
	Fake             *DestinationAzureBlobStorageJSONLinesNewlineDelimitedJSON `tfsdk:"fake"`
	FromField        *FromField                                                `tfsdk:"from_field"`
	OpenAI           *OpenAI                                                   `tfsdk:"open_ai"`
	OpenAICompatible *OpenAICompatible                                         `tfsdk:"open_ai_compatible"`
}
