// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type DestinationDevNullUpdateTestDestination struct {
	DestinationDevNullUpdateTestDestinationSilent *DestinationDevNullUpdateTestDestinationSilent `tfsdk:"destination_dev_null_update_test_destination_silent"`
	DestinationDevNullTestDestinationSilent       *DestinationDevNullTestDestinationSilent       `tfsdk:"destination_dev_null_test_destination_silent"`
}
