// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type SourceOktaAuthorizationMethod struct {
	SourceOktaAuthorizationMethodAPIToken       *SourceK6Cloud                                       `tfsdk:"source_okta_authorization_method_api_token"`
	SourceOktaAuthorizationMethodOAuth20        *DestinationGoogleSheetsAuthenticationViaGoogleOAuth `tfsdk:"source_okta_authorization_method_o_auth2_0"`
	SourceOktaUpdateAuthorizationMethodAPIToken *SourceK6Cloud                                       `tfsdk:"source_okta_update_authorization_method_api_token"`
	SourceOktaUpdateAuthorizationMethodOAuth20  *DestinationGoogleSheetsAuthenticationViaGoogleOAuth `tfsdk:"source_okta_update_authorization_method_o_auth2_0"`
}
