// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type CSVHeaderDefinition struct {
	Autogenerated *Autogenerated `tfsdk:"autogenerated" tfPlanOnly:"true"`
	FromCSV       *FromCSV       `tfsdk:"from_csv" tfPlanOnly:"true"`
	UserProvided  *UserProvided  `tfsdk:"user_provided" tfPlanOnly:"true"`
}
