// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MapperConfiguration struct {
	Encryption    *Encryption    `queryParam:"inline" tfsdk:"encryption" tfPlanOnly:"true"`
	FieldRenaming *FieldRenaming `queryParam:"inline" tfsdk:"field_renaming" tfPlanOnly:"true"`
	Hashing       *Hashing       `queryParam:"inline" tfsdk:"hashing" tfPlanOnly:"true"`
	RowFiltering  *RowFiltering  `queryParam:"inline" tfsdk:"row_filtering" tfPlanOnly:"true"`
}
