// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SourceTiktokMarketing struct {
	AdditionalProperties jsontypes.Normalized                       `tfsdk:"additional_properties"`
	AttributionWindow    types.Int64                                `tfsdk:"attribution_window"`
	Credentials          *SourceTiktokMarketingAuthenticationMethod `tfsdk:"credentials"`
	EndDate              types.String                               `tfsdk:"end_date"`
	IncludeDeleted       types.Bool                                 `tfsdk:"include_deleted"`
	StartDate            types.String                               `tfsdk:"start_date"`
}
