// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SourceDockerhub struct {
	DockerUsername types.String `tfsdk:"docker_username"`
}
