// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type SourceMicrosoftTeamsAuthenticationMechanism struct {
	AuthenticateViaMicrosoft        *AuthenticateViaMicrosoft        `queryParam:"inline" tfsdk:"authenticate_via_microsoft"`
	AuthenticateViaMicrosoftOAuth20 *AuthenticateViaMicrosoftOAuth20 `queryParam:"inline" tfsdk:"authenticate_via_microsoft_o_auth20"`
}
