// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type SourceMongodbV2ClusterType struct {
	MongoDBAtlasReplicaSet *MongoDBAtlasReplicaSet `tfsdk:"mongo_db_atlas_replica_set" tfPlanOnly:"true"`
	SelfManagedReplicaSet  *SelfManagedReplicaSet  `tfsdk:"self_managed_replica_set" tfPlanOnly:"true"`
}
