// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SourceBugsnag struct {
	AuthToken types.String `tfsdk:"auth_token"`
	StartDate types.String `tfsdk:"start_date"`
}
