// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type SubscriptionMethod struct {
	ManuallyAssignAListOfPartitions              *ManuallyAssignAListOfPartitions              `queryParam:"inline" tfsdk:"manually_assign_a_list_of_partitions"`
	SubscribeToAllTopicsMatchingSpecifiedPattern *SubscribeToAllTopicsMatchingSpecifiedPattern `queryParam:"inline" tfsdk:"subscribe_to_all_topics_matching_specified_pattern"`
}
