// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Tag struct {
	Color       types.String `tfsdk:"color"`
	Name        types.String `tfsdk:"name"`
	TagID       types.String `tfsdk:"tag_id"`
	WorkspaceID types.String `tfsdk:"workspace_id"`
}
