// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type TestDestination struct {
	Failing   *Failing   `queryParam:"inline" tfsdk:"failing" tfPlanOnly:"true"`
	Logging   *Logging   `queryParam:"inline" tfsdk:"logging" tfPlanOnly:"true"`
	Silent    *Silent    `queryParam:"inline" tfsdk:"silent" tfPlanOnly:"true"`
	Throttled *Throttled `queryParam:"inline" tfsdk:"throttled" tfPlanOnly:"true"`
}
