// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateDestinationS3Response struct {
	ContentType string
	// Successful operation
	DestinationS3GetResponse *shared.DestinationS3GetResponse
	StatusCode               int
	RawResponse              *http.Response
}
