// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateSourceYouniumResponse struct {
	ContentType string
	// Successful operation
	SourceYouniumGetResponse *shared.SourceYouniumGetResponse
	StatusCode               int
	RawResponse              *http.Response
}
