// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetDestinationAzureBlobStorageRequest struct {
	DestinationID string `pathParam:"style=simple,explode=false,name=destinationId"`
}

type GetDestinationAzureBlobStorageResponse struct {
	ContentType string
	// Get a Destination by the id in the path.
	DestinationAzureBlobStorageGetResponse *shared.DestinationAzureBlobStorageGetResponse
	StatusCode                             int
	RawResponse                            *http.Response
}
